### ISSUE TITLE
SNMP and ping checks running from different containers

### ISSUE THREAD

**Issue by zippanto** [librenms/docker#60]
In our network infrastructure we have got a dedicated network for running monitoring software. However we consider that adding an interface (and so IP) in this network on the Docker host is a security risk, so we always use macvlan network on containers.

This is what we've done with LibreNMS and we have assigned an IP to the "librenms" container in the stack. We then created the SNMP rules on our network devices. After that we could add devices successfully. However after that the ping and SNMP checks are still failing.

I eventually found that the ongoing checks are actually running from the "librenms_cron" container.

It doesn't feel right that we need to add two IPs to all SNMP rule.

Is there any reason why these two containers need to be separate?

**Comment by crazy-max** [comment]
@zippanto Sidecar containers is a common pattern with Docker to address a single concern per container. For LibreNMS, each part has its own responsibilities (web, cron and syslog-ng) and each solves a different problem. This also makes it possible to have very distinct logs.

**Comment by zippanto** [comment]
@crazy-max I appreciate what you are saying, but isn't it a contradiction that these two distinct containers are addressing single concerns yet they are both doing the same function eg. SNMP polling when creating the device vs. recurring SNMP polling?

**Comment by zippanto** [comment]
@crazy-max is this the end of discussion?

**Comment by crazy-max** [comment]
@zippanto I think @murrant can explain better than me, specially with the new dispatcher service.

**Comment by murrant** [comment]
When adding devices checks are run from the webserver, you can easily always check the "force add" option when adding devices. This prevents all checks from being run.  The poller will attempt to discover and poll the device and you will be able to see if that failed shortly from within the webui.

Extra info:
This is due to the fact that there is no way to communicate with the poller directly from webui.  There are plans to make this change, but that is a lot of restructuring and it is not near term.

**Comment by zippanto** [comment]
@murrant thank you, that is an acceptable solution for me.
